name = "nlesolver-fortran"
author = "Jacob Williams"
copyright  = "Copyright (c) 2021-2022, Jacob Williams"
license = "BSD-3"
description = "Nonlinear Equation Solver with Modern Fortran"
homepage = "https://github.com/jacobwilliams/nlesolver-fortran"
keywords = ["nle solver"]

[build]
auto-executables = false
auto-examples = false
auto-tests = false
link = ["lapack", "blas"]

[library]
source-dir = "src"

[dependencies]
fmin = { git="https://github.com/jacobwilliams/fmin.git", tag="1.1.0" }

[install]
library = true

[[test]]
name = "nlesolver_test_1"
source-dir = "tests"
main = "nlesolver_test_1.f90"
