name = "nlesolver-fortran"
author = "Jacob Williams"
copyright  = "Copyright (c) 2021-2022, Jacob Williams"
license = "BSD-3"
description = "Nonlinear Equation Solver with Modern Fortran"
homepage = "https://github.com/jacobwilliams/nlesolver-fortran"
keywords = ["nle solver"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true
link = ["lapack", "blas"]

[library]
source-dir = "src"

[dependencies]
fmin = { git="https://github.com/jacobwilliams/fmin.git", tag="1.1.0" }
LSQR = { git="https://github.com/jacobwilliams/LSQR", tag="1.1.0" }
lusol = { git="https://github.com/jacobwilliams/lusol" }

[install]
library = true
