adjust_x_for_bounds – nlesolver-fortran
adjust_x_for_bounds Subroutine
17 statements
Source File
private subroutine adjust_x_for_bounds(me, x)
if necessary, adjust the x vector to be within the bounds.
Type Bound
nlesolver_type
Arguments
Type Intent Optional Attributes Name
class(nlesolver_type), intent(inout) :: me
real(kind=wp), intent(inout), dimension(me%n) :: x
the x vector to adjust
Calls
Called by
Source Code
    subroutine adjust_x_for_bounds(me,x)
    implicit none
    class(nlesolver_type),intent(inout) :: me
    real(wp),dimension(me%n),intent(inout) :: x  !! the `x` vector to adjust
    integer :: i !! counter
    if (me%bounds_mode==1) then
        ! x = min(max(x,me%xlow),me%xupp)
        do i = 1, me%n
            if (x(i)<me%xlow(i)) then
                x(i) = me%xlow(i)
                if (me%verbose) write(me%iunit, '(A)') 'x('//int2str(i)//') < xlow(i) : adjusting to lower bound'
            else if (x(i)>me%xupp(i)) then
                x(i) = me%xupp(i)
                if (me%verbose) write(me%iunit, '(A)') 'x('//int2str(i)//') > xupp(i) : adjusting to upper bound'
            end if
        end do
    end if
    end subroutine adjust_x_for_bounds
Call graph
adjust_x_for_bounds calls int2str
backtracking_linesearch calls adjust_x_for_bounds
exact_linesearch calls adjust_x_for_bounds
fixed_point_linesearch calls adjust_x_for_bounds
nlesolver_solver calls adjust_x_for_bounds
simple_step calls adjust_x_for_bounds