int2str – nlesolver-fortran
int2str Function
12 statements
Source File
private function int2str(i) result(s)
Convert an integer to a string. Works for up to 256 digits.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
integer to convert
Return Value character(len=:), allocatable
string result
Called by
Source Code
    function int2str(i) result(s)
        integer, intent(in) :: i !! integer to convert
        character(len=:),allocatable :: s !! string result
        character(len=256) :: tmp !! temp string
        integer :: iostat !! write `iostat` code
        write(tmp,fmt=*,iostat=iostat) i
        if (iostat/=0) then
            s = '****'
        else
            s = trim(adjustl(tmp))
        end if
    end function int2str
Call graph
adjust_x_for_bounds calls int2str
set_status calls int2str
backtracking_linesearch calls adjust_x_for_bounds
exact_linesearch calls adjust_x_for_bounds
fixed_point_linesearch calls adjust_x_for_bounds
initialize_nlesolver_variables calls set_status
nlesolver_solver calls adjust_x_for_bounds, set_status
simple_step calls adjust_x_for_bounds