real2str – nlesolver-fortran
real2str Function
12 statements
Source File
private function real2str(r) result(s)
Convert a real to a string. Works for up to 256 digits.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: r
real to convert
Return Value character(len=:), allocatable
string result
Called by
Source Code
    function real2str(r) result(s)
        real(wp), intent(in) :: r !! real to convert
        character(len=:),allocatable :: s !! string result
        character(len=256) :: tmp !! temp string
        integer :: iostat !! write `iostat` code
        write(tmp,fmt=*,iostat=iostat) r
        if (iostat/=0) then
            s = '****'
        else
            s = trim(adjustl(tmp))
        end if
    end function real2str
Call graph
set_status calls real2str
adjust_search_direction calls set_status
initialize_nlesolver_variables calls set_status
nlesolver_solver calls set_status
backtracking_linesearch calls adjust_search_direction
exact_linesearch calls adjust_search_direction
fixed_point_linesearch calls adjust_search_direction
simple_step calls adjust_search_direction